#!/bin/sh

# You need npm to use this script
command -v npm > /dev/null 2>&1 || { echo >&2 "I require npm but it's not installed.  Aborting."; exit 1; }

# Barebones dependencies installation
npm install react
npm install react-dom
npm install webpack --save-dev
npm install webpack-cli --save-dev
npm install webpack-dev-server --save-dev
npm install @babel/core --save-dev
npm install babel-loader --save-dev
npm install @babel/preset-react --save-dev
npm install @babel/preset-env --save-dev
npm install @babel/plugin-transform-runtime --save-dev
npm install @babel/runtime --save-dev
npm install html-webpack-plugin --save-dev
